// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjGDtbnIoRW2zAH9x5hETdlcUj9B2qK6A',
    appId: '1:766239104674:web:eecc299670c334782681fb',
    messagingSenderId: '766239104674',
    projectId: 'learningauth-24690',
    authDomain: 'learningauth-24690.firebaseapp.com',
    storageBucket: 'learningauth-24690.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCerAaXmSpsw-No5HeicglVeuEMqASIAc',
    appId: '1:766239104674:android:72c03183229beeae2681fb',
    messagingSenderId: '766239104674',
    projectId: 'learningauth-24690',
    storageBucket: 'learningauth-24690.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdnz04qWXAubZlfOCAHFt1omTijKBrEOQ',
    appId: '1:766239104674:ios:69e43e319ce94c652681fb',
    messagingSenderId: '766239104674',
    projectId: 'learningauth-24690',
    storageBucket: 'learningauth-24690.appspot.com',
    androidClientId: '766239104674-aqhnnkinh8l598pr76ci8qut9r87tc4g.apps.googleusercontent.com',
    iosClientId: '766239104674-gl9hh9rb9uhjmq3rcia38e5645ji3nea.apps.googleusercontent.com',
    iosBundleId: 'com.example.googleAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdnz04qWXAubZlfOCAHFt1omTijKBrEOQ',
    appId: '1:766239104674:ios:69e43e319ce94c652681fb',
    messagingSenderId: '766239104674',
    projectId: 'learningauth-24690',
    storageBucket: 'learningauth-24690.appspot.com',
    androidClientId: '766239104674-aqhnnkinh8l598pr76ci8qut9r87tc4g.apps.googleusercontent.com',
    iosClientId: '766239104674-gl9hh9rb9uhjmq3rcia38e5645ji3nea.apps.googleusercontent.com',
    iosBundleId: 'com.example.googleAuth',
  );
}
